// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akjicohnyrarskgfejbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFramljb2hueXJhcnNrZ2ZlamJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODI2NDYsImV4cCI6MjA3NDU1ODY0Nn0.UnC6r2AiBXOfMX2iMX3zJCOtUWu3tLScwtmY_IEzqRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});